### PR TITLE
fix symfony 5.x upgrade

### PR DESCRIPTION
**Pull request by jwong-dayspring**
- Fix checking `User.isActive` field on login
- Fix tests
- Restore backwards compatibility with Symfony 4.4

### CODE REVIEW

**Review by dposner-dayspring — COMMENTED** [review]
i had to remove UserPasswordEncoderInterface and use UserPasswordHasherInterface instead to get it working.  not sure if we can just change it back?

**Comment by jwong-dayspring** [comment]
> i had to remove UserPasswordEncoderInterface and use UserPasswordHasherInterface instead to get it working. not sure if we can just change it back?

It looks like `UserPasswordHasherInterface` is new for Symfony 5.3. We'll probably need to change to it before we upgrade to Symfony 6.x, but for 5.x we should be okay with `UserPasswordEncoderInterface`. Keeping `UserPasswordEncoderInterface` also preserves backward compatibility with Symfony 4.4 and eases the migration to Symfony 5.x.

**Comment by dposner-dayspring** [comment]
@jwong-dayspring - i would not have changed the password encoder to hasher if had been working under 5.4.   this is making me uncomfortable and we already had goed sign off on the updated staging.

**Review by dposner-dayspring — DISMISSED** [review]
ok.  will confirm password encoder works in symfony 5.4.

**Pull request merged**
